import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import Stripe from "stripe";
import { normalizeReferralCode } from "@/app/lib/referral";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type WizardCheckoutRequest = {
  riskMode?: "Conservative" | "Balanced" | "Growth" | "Aggressive";
  investmentHorizon?: "< 1 Year" | "1-3 Years" | "3+ Years";
  portfolioSegment?: "Bluechips" | "Memecoins" | "Gaming" | "Yield Farm";
  includeCertifiedDecisionRecord?: boolean;
  resultEmail?: string;
  promoCode?: string;
  referralCode?: string;
  referralUserId?: string;
};

const STRIPE_ALLOCATION_PRICE_CENTS = 1900;
const STRIPE_REPORT_ADD_ON_CENTS = 1500;
const STRIPE_ALLOCATION_PRICE_ID = process.env.STRIPE_SELUN_ALLOCATION_PRICE_ID?.trim() || "";
const STRIPE_REPORT_PRICE_ID = process.env.STRIPE_SELUN_REPORT_PRICE_ID?.trim() || "";

function getStripeClient() {
  const secretKey = process.env.STRIPE_SECRET_KEY?.trim();
  if (!secretKey) {
    throw new Error("STRIPE_SECRET_KEY is not configured.");
  }

  return new Stripe(secretKey);
}

function getSiteUrl(req: Request) {
  const configured = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  if (configured) {
    return configured.replace(/\/+$/, "");
  }

  return new URL(req.url).origin;
}

function buildCheckoutReturnUrl(siteUrl: string, params: Record<string, string>): string {
  const url = new URL("/wizard", siteUrl);
  for (const [key, value] of Object.entries(params)) {
    url.searchParams.set(key, value);
  }

  // Stripe replaces the raw placeholder token. If the token is URL-encoded,
  // Stripe leaves it untouched and the confirm route receives a fake session id.
  return url
    .toString()
    .replace(encodeURIComponent("{CHECKOUT_SESSION_ID}"), "{CHECKOUT_SESSION_ID}");
}

function createDecisionId() {
  return `SELUN-CARD-${Date.now()}-${randomUUID().slice(0, 8)}`.replace(/[^A-Za-z0-9-_]/g, "-");
}

function createLineItem(params: {
  priceId?: string;
  amountCents: number;
  name: string;
  description: string;
}): Stripe.Checkout.SessionCreateParams.LineItem {
  if (params.priceId) {
    return {
      quantity: 1,
      price: params.priceId,
    };
  }

  return {
    quantity: 1,
    price_data: {
      currency: "usd",
      unit_amount: params.amountCents,
      product_data: {
        name: params.name,
        description: params.description,
      },
    },
  };
}

function isRiskMode(value: string | undefined): value is WizardCheckoutRequest["riskMode"] {
  return value === "Conservative" || value === "Balanced" || value === "Growth" || value === "Aggressive";
}

function isInvestmentHorizon(value: string | undefined): value is WizardCheckoutRequest["investmentHorizon"] {
  return value === "< 1 Year" || value === "1-3 Years" || value === "3+ Years";
}

function isPortfolioSegment(value: string | undefined): value is WizardCheckoutRequest["portfolioSegment"] {
  return value === "Bluechips" || value === "Memecoins" || value === "Gaming" || value === "Yield Farm";
}

function isValidEmail(value: string | undefined) {
  if (!value) return true;
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

export async function POST(req: Request): Promise<NextResponse> {
  let payload: WizardCheckoutRequest;

  try {
    payload = (await req.json()) as WizardCheckoutRequest;
  } catch {
    return NextResponse.json({ success: false, error: "Invalid card checkout payload." }, { status: 400 });
  }

  if (!isRiskMode(payload.riskMode) || !isInvestmentHorizon(payload.investmentHorizon) || !isPortfolioSegment(payload.portfolioSegment)) {
    return NextResponse.json(
      { success: false, error: "Risk tolerance, investment timeframe, and portfolio segment are required." },
      { status: 400 },
    );
  }

  const resultEmail = payload.resultEmail?.trim()?.toLowerCase() || "";
  if (!isValidEmail(resultEmail)) {
    return NextResponse.json({ success: false, error: "Enter a valid results email or leave it blank." }, { status: 400 });
  }

  const referralCode = normalizeReferralCode(payload.referralCode);
  const referralUserId = payload.referralUserId?.trim() || "";

  try {
    const stripe = getStripeClient();
    const siteUrl = getSiteUrl(req);
    const decisionId = createDecisionId();
    const includeReport = Boolean(payload.includeCertifiedDecisionRecord);
    const lineItems: Stripe.Checkout.SessionCreateParams.LineItem[] = [
      createLineItem({
        priceId: STRIPE_ALLOCATION_PRICE_ID,
        amountCents: STRIPE_ALLOCATION_PRICE_CENTS,
        name: "Selun Allocation",
        description: "Structured crypto allocation generated by the Selun wizard.",
      }),
    ];

    if (includeReport) {
      lineItems.push(
        createLineItem({
          priceId: STRIPE_REPORT_PRICE_ID,
          amountCents: STRIPE_REPORT_ADD_ON_CENTS,
          name: "Certified Decision Report",
          description: "Formal Selun allocation report with decision rationale and market context.",
        }),
      );
    }

    const successUrl = buildCheckoutReturnUrl(siteUrl, {
      stripe_checkout: "success",
      session_id: "{CHECKOUT_SESSION_ID}",
    });
    const cancelUrl = buildCheckoutReturnUrl(siteUrl, {
      stripe_checkout: "cancelled",
    });

    const sessionParams: Stripe.Checkout.SessionCreateParams = {
      mode: "payment",
      payment_method_types: ["card"],
      allow_promotion_codes: true,
      payment_intent_data: {
        metadata: {
          source: "selun_wizard",
          decisionId,
          riskMode: payload.riskMode ?? "",
          investmentHorizon: payload.investmentHorizon ?? "",
          portfolioSegment: payload.portfolioSegment ?? "",
          includeCertifiedDecisionRecord: includeReport ? "true" : "false",
          resultEmail: resultEmail || "",
          ...(referralCode ? { referralCode } : {}),
          ...(referralUserId ? { referralUserId } : {}),
        },
      },
      success_url: successUrl,
      cancel_url: cancelUrl,
      customer_email: resultEmail || undefined,
      line_items: lineItems,
      metadata: {
        source: "selun_wizard",
        decisionId,
        riskMode: payload.riskMode ?? "",
        investmentHorizon: payload.investmentHorizon ?? "",
        portfolioSegment: payload.portfolioSegment ?? "",
        includeCertifiedDecisionRecord: includeReport ? "true" : "false",
        resultEmail: resultEmail || "",
        ...(referralCode ? { referralCode } : {}),
        ...(referralUserId ? { referralUserId } : {}),
      },
    };

    const session = await stripe.checkout.sessions.create(sessionParams);

    if (!session.url) {
      throw new Error("Stripe checkout session did not return a redirect URL.");
    }

    return NextResponse.json({
      success: true,
      sessionId: session.id,
      decisionId,
      checkoutUrl: session.url,
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : "Failed to start card checkout." },
      { status: 500 },
    );
  }
}
